### ISSUE TITLE
When a notification is unmuted it is not removed from the Muted category list

### ISSUE THREAD

**Issue by NRKirby** [patriksvensson/ghostly#5] opened 2022-01-03 18:23 UTC
**Describe the bug**

When a notification is unmuted it is not removed from the Muted category list

**Steps to reproduce the behavior:**

1. Mute a notification
2. Click on the "Muted" category
3. Unmute the notification

**Expected behavior**

The notification should be removed from the list

**Comments**

This may not be a bug per se but I think fixing this would improve UX. 

I've got a PR ready to go if you'll accept it? :thumbsup:

**Comment by patriksvensson** [comment] 2022-01-03 18:40
@NRKirby Thanks for reporting this!
It's actually like that by design, since it's convenient if you click the wrong button. The same goes for starring items.

**Comment by NRKirby** [comment] 2022-01-03 18:46
No worries! I wasn't 100% sure if this was the intended behaviour so glad I opened an issue in the first instance. Feel free to close this! :blush:

**Comment by patriksvensson** [comment] 2022-01-03 18:50
@NRKirby I appreciate that you took the time to open the issue.
If this is something you feel strongly about, we could always make it a setting.

**Comment by patriksvensson** [comment] 2022-01-04 07:47
@NRKirby I'm closing this issue for now. Feel free to re-open it if you want to continue discussing this!

**Closed by patriksvensson** 2022-01-04 07:47 UTC
Labels: bug
